# netlify.toml — minimal and valid
[build]
  command = ""      # static site, no build step
  publish = "."

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "18"
